export interface Project {
  id: string;
  slug: string;
  title: string;
  tagline: string;
  description: string;
  category: string;
  thumbnail: string;
  images: string[];
  techStack: string[];
  goals: string[];
  challenges: string[];
  solutions: string[];
  results: string[];
  duration: string;
  clientIndustry: string;
}

export const projects: Project[] = [
  {
    id: "1",
    slug: "ecommerce-platform",
    title: "NextGen E-Commerce Platform",
    tagline: "Modern online shopping experience with AI-powered recommendations",
    description: "A cutting-edge e-commerce platform built for a fashion retail brand, featuring seamless checkout, real-time inventory management, and personalized product recommendations powered by machine learning.",
    category: "E-Commerce",
    thumbnail: "https://images.unsplash.com/photo-1557821552-17105176677c?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&h=800&fit=crop",
    ],
    techStack: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "TailwindCSS", "AWS"],
    goals: [
      "Create a seamless shopping experience across all devices",
      "Implement AI-powered product recommendations",
      "Integrate secure payment processing",
      "Build scalable architecture to handle 10,000+ daily visitors",
    ],
    challenges: [
      "Complex product variant management system",
      "Real-time inventory synchronization across multiple warehouses",
      "Optimizing page load times with large product catalogs",
      "Implementing secure payment processing with multiple providers",
    ],
    solutions: [
      "Developed custom variant management system with intuitive admin interface",
      "Implemented WebSocket-based real-time inventory updates",
      "Utilized Next.js ISR and image optimization for fast page loads",
      "Integrated Stripe with PCI-compliant payment flows",
    ],
    results: [
      "40% increase in conversion rates",
      "Page load times reduced by 60%",
      "Successfully handles 15,000+ daily active users",
      "Customer satisfaction score improved to 4.8/5",
    ],
    duration: "3 months",
    clientIndustry: "Fashion Retail",
  },
  {
    id: "2",
    slug: "healthcare-app",
    title: "HealthConnect Telemedicine App",
    tagline: "Connecting patients with healthcare providers instantly",
    description: "A HIPAA-compliant telemedicine platform that enables video consultations, prescription management, and electronic health records access for patients and healthcare providers.",
    category: "Healthcare",
    thumbnail: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&h=800&fit=crop",
    ],
    techStack: ["React Native", "Node.js", "MongoDB", "WebRTC", "AWS", "Socket.io"],
    goals: [
      "Build HIPAA-compliant healthcare platform",
      "Enable high-quality video consultations",
      "Implement secure patient data management",
      "Create intuitive interface for all age groups",
    ],
    challenges: [
      "Ensuring HIPAA compliance across all features",
      "Maintaining video quality on low-bandwidth connections",
      "Securing sensitive patient health information",
      "Supporting both iOS and Android platforms",
    ],
    solutions: [
      "Implemented end-to-end encryption for all communications",
      "Used adaptive bitrate streaming for video calls",
      "Built multi-factor authentication and role-based access control",
      "Developed shared React Native codebase with platform-specific optimizations",
    ],
    results: [
      "10,000+ successful consultations in first 3 months",
      "99.9% uptime maintained",
      "Average consultation rating of 4.7/5",
      "Reduced patient wait times by 70%",
    ],
    duration: "5 months",
    clientIndustry: "Healthcare",
  },
  {
    id: "3",
    slug: "fintech-dashboard",
    title: "InvestPro Analytics Dashboard",
    tagline: "Real-time financial data visualization and portfolio management",
    description: "A sophisticated fintech dashboard for investment firms, providing real-time market data, portfolio analytics, and automated reporting capabilities.",
    category: "FinTech",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop",
    ],
    techStack: ["React", "TypeScript", "Python", "FastAPI", "PostgreSQL", "Redis", "Chart.js"],
    goals: [
      "Display real-time market data with minimal latency",
      "Provide comprehensive portfolio analytics",
      "Enable automated report generation",
      "Ensure bank-level security standards",
    ],
    challenges: [
      "Processing and visualizing large datasets in real-time",
      "Implementing complex financial calculations accurately",
      "Managing multiple data source integrations",
      "Ensuring sub-second response times for critical data",
    ],
    solutions: [
      "Built WebSocket-based real-time data pipeline",
      "Implemented Redis caching layer for frequently accessed data",
      "Created modular data integration framework",
      "Optimized database queries and added strategic indexes",
    ],
    results: [
      "Real-time data updates with <100ms latency",
      "Reduced report generation time by 85%",
      "Managing $50M+ in tracked assets",
      "99.99% system reliability",
    ],
    duration: "4 months",
    clientIndustry: "Financial Services",
  },
  {
    id: "4",
    slug: "restaurant-management",
    title: "RestaurantOS Management System",
    tagline: "Complete restaurant operations management solution",
    description: "An all-in-one restaurant management system featuring POS integration, inventory tracking, online ordering, and customer loyalty programs.",
    category: "Hospitality",
    thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop",
    ],
    techStack: ["Vue.js", "Node.js", "Express", "MySQL", "Stripe", "TailwindCSS"],
    goals: [
      "Streamline restaurant operations from ordering to billing",
      "Implement real-time kitchen display system",
      "Enable online ordering and delivery tracking",
      "Build customer loyalty and rewards program",
    ],
    challenges: [
      "Synchronizing data across multiple devices in real-time",
      "Managing complex menu customizations and modifiers",
      "Integrating with existing POS hardware",
      "Handling offline functionality for unstable connections",
    ],
    solutions: [
      "Built real-time synchronization using WebSockets",
      "Created flexible menu management system with unlimited customization",
      "Developed universal POS integration layer",
      "Implemented progressive web app with offline-first architecture",
    ],
    results: [
      "Reduced order processing time by 45%",
      "Increased online orders by 200%",
      "Kitchen efficiency improved by 30%",
      "Customer retention increased by 25%",
    ],
    duration: "3 months",
    clientIndustry: "Food & Beverage",
  },
  {
    id: "5",
    slug: "education-platform",
    title: "LearnHub Education Platform",
    tagline: "Interactive online learning with live classes and assessments",
    description: "A comprehensive e-learning platform featuring live classes, interactive assessments, progress tracking, and collaborative tools for students and educators.",
    category: "Education",
    thumbnail: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=800&fit=crop",
    ],
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "WebRTC", "AWS S3", "Stripe"],
    goals: [
      "Create engaging online learning environment",
      "Enable live interactive classes with up to 100 participants",
      "Implement adaptive assessment system",
      "Provide detailed analytics for educators and parents",
    ],
    challenges: [
      "Ensuring stable video streaming for large classes",
      "Building interactive whiteboard and screen sharing features",
      "Creating fair and secure assessment system",
      "Scaling to support thousands of concurrent users",
    ],
    solutions: [
      "Leveraged AWS media services for scalable video delivery",
      "Built custom WebRTC-based collaboration tools",
      "Implemented proctoring features and plagiarism detection",
      "Designed microservices architecture for horizontal scaling",
    ],
    results: [
      "5,000+ active students within 2 months of launch",
      "98% class attendance rate",
      "Student engagement scores increased by 40%",
      "Teacher productivity improved by 35%",
    ],
    duration: "6 months",
    clientIndustry: "Education",
  },
  {
    id: "6",
    slug: "web3-nft-marketplace",
    title: "ArtVerse NFT Marketplace",
    tagline: "Decentralized marketplace for digital art and collectibles",
    description: "A Web3-powered NFT marketplace built on Ethereum, featuring gasless transactions, creator royalties, and social features for artists and collectors.",
    category: "Web3",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1644361566696-3d442b5b482a?w=1200&h=800&fit=crop",
    ],
    techStack: ["React", "Solidity", "Ethers.js", "IPFS", "The Graph", "Hardhat", "Node.js"],
    goals: [
      "Build user-friendly Web3 marketplace for non-crypto natives",
      "Implement gasless transactions to improve accessibility",
      "Ensure secure smart contract architecture",
      "Create social features to build community",
    ],
    challenges: [
      "Simplifying Web3 wallet integration for mainstream users",
      "Optimizing gas costs for minting and trading",
      "Ensuring smart contract security and audit readiness",
      "Managing high-resolution artwork storage efficiently",
    ],
    solutions: [
      "Integrated social login with wallet abstraction",
      "Implemented meta-transactions for gasless experience",
      "Conducted thorough smart contract audits and testing",
      "Used IPFS for decentralized storage with CDN caching",
    ],
    results: [
      "$2M+ in NFT trading volume in first quarter",
      "1,200+ artists onboarded",
      "Zero smart contract vulnerabilities in audit",
      "Average transaction time of 3 seconds",
    ],
    duration: "4 months",
    clientIndustry: "Blockchain",
  },
  {
    id: "7",
    slug: "sports-fitness-app",
    title: "FitTrack Pro",
    tagline: "Comprehensive fitness tracking and social platform",
    description: "A mobile-first fitness application with workout tracking, nutrition logging, social challenges, and AI-powered personalized training plans.",
    category: "Health & Fitness",
    thumbnail: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=800&fit=crop",
    ],
    techStack: ["React Native", "Firebase", "TensorFlow Lite", "Chart.js", "Stripe"],
    goals: [
      "Create engaging fitness tracking experience",
      "Build social features for motivation and competition",
      "Implement AI-powered workout recommendations",
      "Enable seamless offline tracking",
    ],
    challenges: [
      "Processing sensor data from multiple wearables",
      "Optimizing battery consumption for continuous tracking",
      "Building accurate calorie and macro calculators",
      "Creating engaging social features without compromising privacy",
    ],
    solutions: [
      "Developed unified API for multiple wearable integrations",
      "Implemented background task optimization",
      "Built ML models for personalized nutrition recommendations",
      "Designed privacy-first social sharing with granular controls",
    ],
    results: [
      "50,000+ active users within 6 months",
      "Average user engagement of 5+ days per week",
      "30% improvement in user retention vs competitors",
      "4.9/5 app store rating",
    ],
    duration: "5 months",
    clientIndustry: "Health & Fitness",
  },
  {
    id: "8",
    slug: "real-estate-platform",
    title: "PropertyHub Real Estate",
    tagline: "Modern real estate platform with virtual tours and AI matching",
    description: "An advanced real estate platform featuring virtual property tours, AI-powered property matching, mortgage calculators, and seamless agent-client communication.",
    category: "Real Estate",
    thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&h=800&fit=crop",
    ],
    techStack: ["Next.js", "Three.js", "PostgreSQL", "Redis", "AWS", "Twilio"],
    goals: [
      "Revolutionize property search with virtual reality tours",
      "Implement intelligent property matching based on preferences",
      "Streamline communication between buyers and agents",
      "Provide comprehensive market analytics",
    ],
    challenges: [
      "Rendering high-quality 3D virtual tours efficiently",
      "Processing and indexing large property databases",
      "Implementing accurate price estimation algorithms",
      "Ensuring fast search with complex filters",
    ],
    solutions: [
      "Optimized 3D asset loading with progressive enhancement",
      "Built Elasticsearch integration for fast property search",
      "Developed ML models trained on local market data",
      "Implemented Redis caching for frequently accessed properties",
    ],
    results: [
      "2,500+ properties listed in first quarter",
      "Virtual tour engagement rate of 85%",
      "Average search time reduced to under 500ms",
      "30% increase in successful property matches",
    ],
    duration: "4 months",
    clientIndustry: "Real Estate",
  },
  {
    id: "9",
    slug: "logistics-dashboard",
    title: "ShipFlow Logistics Manager",
    tagline: "Enterprise logistics and supply chain management platform",
    description: "A comprehensive logistics management system with real-time shipment tracking, route optimization, inventory management, and automated notifications.",
    category: "Logistics",
    thumbnail: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop",
    ],
    techStack: ["Vue.js", "Node.js", "PostgreSQL", "Redis", "Google Maps API", "Socket.io"],
    goals: [
      "Provide end-to-end visibility into supply chain operations",
      "Optimize delivery routes to reduce costs and time",
      "Enable real-time tracking for all stakeholders",
      "Automate inventory management and reordering",
    ],
    challenges: [
      "Processing millions of location updates in real-time",
      "Optimizing complex multi-stop delivery routes",
      "Integrating with multiple carrier APIs",
      "Handling peak season traffic spikes",
    ],
    solutions: [
      "Built event-driven architecture with message queues",
      "Implemented genetic algorithm for route optimization",
      "Created unified carrier integration abstraction layer",
      "Designed auto-scaling infrastructure on AWS",
    ],
    results: [
      "Reduced delivery costs by 25%",
      "Improved on-time delivery rate to 98%",
      "Real-time tracking accuracy of 99.5%",
      "Supporting 10,000+ daily shipments",
    ],
    duration: "6 months",
    clientIndustry: "Logistics & Supply Chain",
  },
  {
    id: "10",
    slug: "music-streaming-app",
    title: "SoundWave Music Platform",
    tagline: "Premium music streaming with social features",
    description: "A modern music streaming platform with high-quality audio, curated playlists, social sharing, and AI-powered music discovery features.",
    category: "Entertainment",
    thumbnail: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1200&h=800&fit=crop",
    ],
    techStack: ["React", "Node.js", "MongoDB", "AWS S3", "Stripe", "Spotify API"],
    goals: [
      "Deliver high-quality audio streaming experience",
      "Create personalized music discovery for each user",
      "Build social features for sharing music and playlists",
      "Support offline downloads for premium users",
    ],
    challenges: [
      "Streaming high-quality audio without buffering",
      "Managing licensing and royalty calculations",
      "Building accurate music recommendation engine",
      "Storing and serving millions of audio files efficiently",
    ],
    solutions: [
      "Implemented adaptive bitrate streaming",
      "Built automated licensing and royalty management system",
      "Developed collaborative filtering and deep learning models",
      "Used CDN with edge caching for global content delivery",
    ],
    results: [
      "100,000+ registered users in first year",
      "Average listening session of 45+ minutes",
      "99.9% uptime maintained",
      "User satisfaction score of 4.7/5",
    ],
    duration: "5 months",
    clientIndustry: "Entertainment",
  },
  {
    id: "11",
    slug: "travel-booking-platform",
    title: "Wanderlust Travel Hub",
    tagline: "All-in-one travel planning and booking experience",
    description: "A comprehensive travel platform offering flight booking, hotel reservations, itinerary planning, and local experiences all in one seamless interface.",
    category: "Travel",
    thumbnail: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&h=800&fit=crop",
    ],
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "Redis", "Amadeus API", "Stripe"],
    goals: [
      "Simplify travel booking across multiple services",
      "Provide best price comparison from multiple providers",
      "Create intelligent itinerary suggestions",
      "Enable collaborative trip planning for groups",
    ],
    challenges: [
      "Aggregating real-time pricing from multiple APIs",
      "Handling complex booking flows with multiple providers",
      "Managing cancellations and refunds across systems",
      "Providing accurate availability and pricing",
    ],
    solutions: [
      "Built resilient API gateway with circuit breakers",
      "Implemented state machine for booking workflows",
      "Created unified refund and cancellation service",
      "Developed caching strategy for frequently accessed data",
    ],
    results: [
      "5,000+ bookings in first 3 months",
      "Average savings of 15% vs booking separately",
      "95% booking success rate",
      "Customer satisfaction of 4.8/5",
    ],
    duration: "4 months",
    clientIndustry: "Travel & Tourism",
  },
  {
    id: "12",
    slug: "crm-sales-platform",
    title: "SalesForce Pro CRM",
    tagline: "Intelligent CRM with sales automation and analytics",
    description: "A powerful customer relationship management platform with sales pipeline tracking, automated workflows, email integration, and comprehensive analytics.",
    category: "SaaS",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&h=800&fit=crop",
    ],
    techStack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "SendGrid", "Zapier"],
    goals: [
      "Streamline sales processes with automation",
      "Provide comprehensive sales analytics and forecasting",
      "Integrate with popular email and calendar platforms",
      "Enable custom workflow creation without coding",
    ],
    challenges: [
      "Designing flexible workflow engine",
      "Handling large datasets for analytics",
      "Ensuring data security and compliance",
      "Creating intuitive UI for complex features",
    ],
    solutions: [
      "Built visual workflow builder with drag-and-drop interface",
      "Implemented columnar database for fast analytics queries",
      "Applied end-to-end encryption and GDPR compliance",
      "Created component-based design system for consistency",
    ],
    results: [
      "200+ companies using the platform",
      "Average sales cycle reduced by 20%",
      "50% increase in deal closure rates",
      "99.9% data security uptime",
    ],
    duration: "6 months",
    clientIndustry: "Business Software",
  },
  {
    id: "13",
    slug: "food-delivery-platform",
    title: "QuickBite Delivery",
    tagline: "Fast and reliable food delivery with real-time tracking",
    description: "A comprehensive food delivery platform connecting customers with restaurants, featuring real-time order tracking, multiple payment options, and intelligent route optimization for delivery partners.",
    category: "Food & Delivery",
    thumbnail: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&h=800&fit=crop",
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&h=800&fit=crop",
    ],
    techStack: ["React Native", "Node.js", "MongoDB", "Redis", "Google Maps API", "Stripe", "Socket.io"],
    goals: [
      "Enable fast and efficient food delivery",
      "Provide real-time order tracking for customers",
      "Optimize delivery routes for drivers",
      "Build comprehensive restaurant management tools",
    ],
    challenges: [
      "Managing real-time location updates for multiple delivery drivers",
      "Coordinating orders between restaurants and drivers",
      "Handling peak hours with high order volumes",
      "Ensuring accurate delivery time predictions",
    ],
    solutions: [
      "Implemented WebSocket-based real-time tracking system",
      "Built intelligent order assignment algorithm",
      "Created auto-scaling infrastructure for peak loads",
      "Developed ML models for delivery time prediction",
    ],
    results: [
      "Average delivery time of 28 minutes",
      "10,000+ orders processed monthly",
      "4.8/5 customer satisfaction rating",
      "Restaurant partner retention rate of 95%",
    ],
    duration: "4 months",
    clientIndustry: "Food & Beverage",
  },
];

